// <auto-generated />
using System;
using GestionSchool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionSchool.Migrations
{
    [DbContext(typeof(SchoolCrudContext))]
    [Migration("20240622022556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionSchool.Models.Curso", b =>
                {
                    b.Property<int>("CodigoCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoCurso"));

                    b.Property<string>("Jornada")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CodigoCurso")
                        .HasName("PK__Cursos__BB0F2318123E0EA9");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("GestionSchool.Models.Estudiante", b =>
                {
                    b.Property<int>("DocumentoIdentidad")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("DocumentoIdentidad")
                        .HasName("PK__Estudian__049E81A881993628");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestionSchool.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("GestionSchool.Models.Matricula", b =>
                {
                    b.Property<int>("CodigoMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoMatricula"));

                    b.Property<int?>("DocumentoIdentidadEstudiante")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.HasKey("CodigoMatricula")
                        .HasName("PK__Matricul__4DF06615C0D739A8");

                    b.HasIndex(new[] { "DocumentoIdentidadEstudiante" }, "IX_Matriculas_DocumentoIdentidadEstudiante");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("GestionSchool.Models.MatriculaCurso", b =>
                {
                    b.Property<int>("CodigoMatricula")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCurso")
                        .HasColumnType("int");

                    b.HasKey("CodigoMatricula", "CodigoCurso")
                        .HasName("PK__Matricul__D6409424BB8FA408");

                    b.HasIndex(new[] { "CodigoCurso" }, "IX_MatriculasCursos_CodigoCurso");

                    b.ToTable("MatriculaCursos");
                });

            modelBuilder.Entity("GestionSchool.Models.ProfesorCurso", b =>
                {
                    b.Property<int>("DocumentoIdentidadProfesor")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCurso")
                        .HasColumnType("int");

                    b.HasKey("DocumentoIdentidadProfesor", "CodigoCurso")
                        .HasName("PK__Profesor__12F1DDC77F77F806");

                    b.HasIndex(new[] { "CodigoCurso" }, "IX_ProfesoresCursos_CodigoCurso");

                    b.ToTable("ProfesorCursos");
                });

            modelBuilder.Entity("GestionSchool.Models.Profesore", b =>
                {
                    b.Property<int>("DocumentoIdentidad")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Profesion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DocumentoIdentidad")
                        .HasName("PK__Profesor__049E81A816F39792");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("GestionSchool.Models.Matricula", b =>
                {
                    b.HasOne("GestionSchool.Models.Estudiante", "DocumentoIdentidadEstudianteNavigation")
                        .WithMany("Matriculas")
                        .HasForeignKey("DocumentoIdentidadEstudiante")
                        .HasConstraintName("FK__Matricula__Docum__3E52440B");

                    b.Navigation("DocumentoIdentidadEstudianteNavigation");
                });

            modelBuilder.Entity("GestionSchool.Models.MatriculaCurso", b =>
                {
                    b.HasOne("GestionSchool.Models.Curso", "Curso")
                        .WithMany("MatriculaCursos")
                        .HasForeignKey("CodigoCurso")
                        .IsRequired()
                        .HasConstraintName("FK__Matricula__Codig__45F365D3");

                    b.HasOne("GestionSchool.Models.Matricula", "Matricula")
                        .WithMany("MatriculaCursos")
                        .HasForeignKey("CodigoMatricula")
                        .IsRequired()
                        .HasConstraintName("FK__Matricula__Codig__44FF419A");

                    b.Navigation("Curso");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("GestionSchool.Models.ProfesorCurso", b =>
                {
                    b.HasOne("GestionSchool.Models.Curso", "Curso")
                        .WithMany("ProfesorCursos")
                        .HasForeignKey("CodigoCurso")
                        .IsRequired()
                        .HasConstraintName("FK__Profesore__Codig__4222D4EF");

                    b.HasOne("GestionSchool.Models.Profesore", "Profesor")
                        .WithMany("ProfesorCursos")
                        .HasForeignKey("DocumentoIdentidadProfesor")
                        .IsRequired()
                        .HasConstraintName("FK__Profesore__Docum__412EB0B6");

                    b.Navigation("Curso");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("GestionSchool.Models.Curso", b =>
                {
                    b.Navigation("MatriculaCursos");

                    b.Navigation("ProfesorCursos");
                });

            modelBuilder.Entity("GestionSchool.Models.Estudiante", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("GestionSchool.Models.Matricula", b =>
                {
                    b.Navigation("MatriculaCursos");
                });

            modelBuilder.Entity("GestionSchool.Models.Profesore", b =>
                {
                    b.Navigation("ProfesorCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
